import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import Wrapper from "@/components/common/Wrapper";
import AccountSection from "@/components/ui/account-section";
import { Toaster } from "@/components/ui/sonner";
import PhoneNavbar from "@/components/common/phone-navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Valimar E Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark`}
      >
        <Wrapper scrollable={true}>
          <Header />
          <AccountSection/>
        </Wrapper>
        {children}
        <Toaster richColors position="top-center" duration={2000} />
        <Wrapper scrollable={false}>
          <Footer />
        </Wrapper>
        <PhoneNavbar />
      </body>
    </html>
  );
}
