import {
  witcher,
  cyberpunk,
  elden,
  reddead,
  hades,
  stardew,
  among,
  darksoul3,
  cult,
  acval,
  hollowknight,
  nomansky,
  starfield,
  baldur,
  spider,
  alanwake2,
  supermario,
  lotf,
  mortal,
  acmirage,
  forza,
  avatar,
  payday3,
  cities2,
} from "./image";

export const special_deal = [
  {
    id: 1,
    name: "The Witcher 3: Wild Hunt",
    price: 39.99,
    discount_price: 19.99,
    percent_discount: 50,
    image: witcher,
  },
  {
    id: 2,
    name: "Cyberpunk 2077",
    price: 59.99,
    discount_price: 29.99,
    percent_discount: 50,
    image: cyberpunk,
  },
  {
    id: 3,
    name: "Elden Ring",
    price: 59.99,
    discount_price: 49.99,
    percent_discount: 16,
    image: elden,
  },
  {
    id: 4,
    name: "Red Dead Redemption 2",
    price: 59.99,
    discount_price: 29.99,
    percent_discount: 50,
    image: reddead,
  },
  {
    id: 5,
    name: "Hades",
    price: 24.99,
    discount_price: 12.49,
    percent_discount: 50,
    image: hades,
  },
  {
    id: 6,
    name: "Stardew Valley",
    price: 14.99,
    discount_price: 9.99,
    percent_discount: 33,
    image: stardew,
  },
  {
    id: 7,
    name: "Among Us",
    price: 4.99,
    discount_price: 3.99,
    percent_discount: 20,
    image: among,
  },
  {
    id: 8,
    name: "Dark Souls III",
    price: 59.99,
    discount_price: 14.99,
    percent_discount: 75,
    image: darksoul3,
  },
  {
    id: 9,
    name: "Cult Of The Lamb",
    price: 24.99,
    discount_price: 12.99,
    percent_discount: 50,
    image: cult,
  },
  {
    id: 10,
    name: "Assassin's Creed Valhalla",
    price: 59.99,
    discount_price: 39.99,
    percent_discount: 33,
    image: acval,
  },
  {
    id: 11,
    name: "Hollow Knight",
    price: 14.99,
    discount_price: 7.49,
    percent_discount: 50,
    image: hollowknight,
  },
  {
    id: 12,
    name: "No Man's Sky",
    price: 59.99,
    discount_price: 29.99,
    percent_discount: 50,
    image: nomansky,
  },
];

export const new_releases = [
  {
    id: 1,
    name: "Starfield",
    price: 69.99,
    discount_price: 59.99,
    percent_discount: 14,
    image: starfield,
  },
  {
    id: 2,
    name: "Baldur's Gate 3",
    price: 59.99,
    discount_price: 49.99,
    percent_discount: 16,
    is_Discount: true,
    image: baldur,
  },
  {
    id: 3,
    name: "Spider-Man 2",
    price: 69.99,
    discount_price: 0,
    percent_discount: 0,
    is_Discount: false,
    image: spider,
  },
  {
    id: 4,
    name: "Alan Wake 2",
    price: 59.99,
    discount_price: 49.99,
    percent_discount: 16,
    is_Discount: true,
    image: alanwake2,
  },
  {
    id: 5,
    name: "Super Mario Bros. Wonder",
    price: 59.99,
    discount_price: 0,
    percent_discount: 0,
    is_Discount: false,
    image: supermario,
  },
  {
    id: 6,
    name: "Lords of the Fallen",
    price: 69.99,
    discount_price: 54.99,
    percent_discount: 21,
    is_Discount: true,
    image: lotf,
  },
  {
    id: 7,
    name: "Mortal Kombat 1",
    price: 69.99,
    discount_price: 0,
    percent_discount: 0,
    is_Discount: false,
    image: mortal,
  },
  {
    id: 8,
    name: "Assassin's Creed Mirage",
    price: 49.99,
    discount_price: 39.99,
    percent_discount: 20,
    is_Discount: true,
    image: acmirage,
  },
  {
    id: 9,
    name: "Forza Motorsport",
    price: 59.99,
    discount_price: 0,
    percent_discount: 0,
    is_Discount: false,
    image: forza,
  },
  {
    id: 10,
    name: "Avatar: Frontiers of Pandora",
    price: 69.99,
    discount_price: 64.99,
    percent_discount: 7,
    is_Discount: true,
    image: avatar,
  },
  {
    id: 11,
    name: "Payday 3",
    price: 39.99,
    discount_price: 29.99,
    percent_discount: 25,
    is_Discount: true,
    image: payday3,
  },
  {
    id: 12,
    name: "Cities: Skylines II",
    price: 49.99,
    discount_price: 0,
    percent_discount: 0,
    is_Discount: false,
    image: cities2,
  },
];

export const features1 = ["Access to all content"];
export const features2 = [
  "Access to all content",
  "10% discount",
  "No delivery fee",
  "Priority customer support",
  "Special effect",
];
export const features3 = [
  "Access to all content",
  "20% discount",
  "No delivery fee",
  "Priority customer support",
  "Special effect",
  "Refund in 7 days",
];
export const features4 = [
  "Access to all content",
  "30% discount, 35% for digital",
  "No delivery fee",
  "Priority customer support",
  "Special effect",
  "Refund in 14 days",
];

export const subcategories = [
  { id: 1, name: "New Release", href: "/category/new-release", description: "Explore the latest games released this month." },
  { id: 2, name: "Upcoming", href: "/category/upcoming", description: "Discover upcoming games and get ready for the launch." },
  { id: 3, name: "Best Sale", href: "/category/best-sale", description: "Find the best deals and discounts on popular games." },
  { id: 4, name: "Action", href: "/category/action", description: "Dive into the thrill of high-paced action games." },
  { id: 5, name: "Horror", href: "/category/horror", description: "Experience spine-chilling horror games that will keep you on edge." },
  { id: 6, name: "Adventure", href: "/category/adventure", description: "Embark on epic journeys and immersive adventures." },
  { id: 7, name: "JRPG", href: "/category/jrpg", description: "Enjoy the best of Japanese RPG games with deep storytelling." },
  { id: 8, name: "Music", href: "/category/music", description: "Play music-inspired games and test your rhythm skills." },
  { id: 9, name: "Puzzle", href: "/category/puzzle", description: "Challenge your mind with creative and engaging puzzle games." },
  { id: 10, name: "Space", href: "/category/space", description: "Explore the vast universe with exciting space-themed games." },
  { id: 11, name: "Simulation", href: "/category/simulation", description: "Experience realistic simulation games that mimic real life." },
  { id: 12, name: "Dating", href: "/category/dating", description: "Discover interactive dating simulation games." },
  { id: 13, name: "Fighting", href: "/category/fighting", description: "Engage in intense battles and showcase your fighting skills." },
  { id: 14, name: "Racing", href: "/category/racing", description: "Feel the adrenaline rush with high-speed racing games." },
  { id: 15, name: "Strategy", href: "/category/strategy", description: "Test your tactical skills with challenging strategy games." },
  { id: 16, name: "Turn-Base", href: "/category/turn-base", description: "Plan and conquer with classic turn-based gameplay." },
  { id: 17, name: "Building", href: "/category/building", description: "Create and manage your world with exciting building games." },
];
